import type { PublicItem } from "./listing.types";
const base: PublicItem = {
  id: "",
  title: "",
  description:
    "Dieses Beispiel zeigt, wie ein Inserat in der Teilebörse aussieht. Es ist kein echtes Angebot.",
  category: "reifen",
  condition: "gebraucht_gut",
  offer_type: "verkauf_bar",
  price_chf: 180,
  photos: [],
  fits: [
    { make: "Volkswagen", model: "Golf 7", year_from: 2012, year_to: 2020 },
  ],
  fits_note: "Bitte die Kompatibilität vor dem Kauf prüfen.",
  manufacturer: "Continental",
  oem_number: "",
  pickup_zip: "8004",
  pickup_canton: "ZH",
  shipping_possible: false,
  negotiable: true,
  swap_for: "",
  status: "available",
  created_at: "2026-10-03T10:00:00Z",
  seller_name: "Marco B.",
  business_slug: null,
  business_name: null,
  payment_mode: null,
  tire_width: 205,
  tire_ratio: 55,
  rim_diameter: 16,
  tire_season: "winter",
  tread_mm: 6.5,
  rim_bolt_pattern: null,
  rim_offset_et: null,
  quantity: 4,
};
export const DEMO_ITEMS: PublicItem[] = [
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000001",
    title: "Winterreifen 205/55 R16 · 4 Stück",
    photos: ["/landing/garage.webp"],
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000002",
    title: "Alufelgen 18 Zoll · 5×112",
    category: "felgen",
    price_chf: 420,
    manufacturer: "BBS",
    rim_diameter: 18,
    rim_bolt_pattern: "5x112",
    tire_width: null,
    tire_ratio: null,
    tire_season: null,
    pickup_zip: "3000",
    pickup_canton: "BE",
    seller_name: "Garage Müller",
    business_name: "Garage Müller",
    condition: "neuwertig",
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000003",
    title: "Dachträger für VW Golf",
    category: "dachträger_anhängerkupplung",
    offer_type: "tausch",
    price_chf: null,
    swap_for: "Veloträger für die Anhängerkupplung",
    pickup_zip: "6003",
    pickup_canton: "LU",
    manufacturer: "Thule",
    tire_width: null,
    tire_ratio: null,
    rim_diameter: null,
    tire_season: null,
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000004",
    title: "Gummimatten · kompletter Satz",
    category: "innenraum",
    offer_type: "gratis",
    price_chf: 0,
    pickup_zip: "9000",
    pickup_canton: "SG",
    manufacturer: "Volkswagen",
    tire_width: null,
    tire_ratio: null,
    rim_diameter: null,
    tire_season: null,
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000005",
    title: "LED-Scheinwerfer links · Golf 7",
    category: "beleuchtung",
    price_chf: 240,
    oem_number: "5G1941035",
    shipping_possible: true,
    pickup_zip: "5000",
    pickup_canton: "AG",
    tire_width: null,
    tire_ratio: null,
    rim_diameter: null,
    tire_season: null,
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000006",
    title: "Sommer-Kompletträder 225/45 R17",
    category: "kompletträder",
    price_chf: 360,
    tire_width: 225,
    tire_ratio: 45,
    rim_diameter: 17,
    tire_season: "sommer",
    pickup_zip: "6300",
    pickup_canton: "ZG",
  },
];
